version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'files-manager_db'
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./mysql:/var/lib/mysql
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    expose:
      - '6379'
    volumes:
      - ./redis:/data
