version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'files-manager_db'
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./mysql:/var/lib/mysql
